"""Tests for issue-local-038: hunt reports stamp the app version/commit they
were generated with, in the report data itself and in both renderers."""

from __future__ import annotations

from backend.threat_hunting.agents.nodes.report_writer import (
    assemble_report,
    render_report_markdown,
    render_report_pdf,
)


def _report(**overrides):
    return assemble_report(
        hunt_package={"id": "pkg-1", "name": "Test", "status": "approved"},
        generation_record={},
        evidence_items=[],
        task_results=[],
        **overrides,
    )


def test_assemble_report_includes_app_version_and_commit():
    from backend import __version__

    report = _report()
    assert report["app_version"] == __version__
    assert "app_commit" in report


def test_assemble_report_commit_reflects_env_var(monkeypatch):
    monkeypatch.setenv("GIT_COMMIT", "abc1234")
    report = _report()
    assert report["app_commit"] == "abc1234"


def test_render_report_markdown_includes_commit(monkeypatch):
    monkeypatch.setenv("GIT_COMMIT", "abc1234")
    report = _report()
    md = render_report_markdown(report)
    assert "abc1234" in md
    assert "Generated By" in md


def test_render_report_pdf_includes_commit(monkeypatch):
    """PDF bytes should be non-empty and generation should not error with
    the new metadata field present (full byte-content isn't practically
    assertable for a PDF, so this is a smoke test)."""
    monkeypatch.setenv("GIT_COMMIT", "abc1234")
    report = _report()
    pdf_bytes = render_report_pdf(report)
    assert isinstance(pdf_bytes, bytes)
    assert len(pdf_bytes) > 0
