"""LangGraph node: report_writer

Assembles the final Hunt Report from all pipeline outputs and execution results.

Two-stage process:
  1. Deterministic assembly — collects all structured data (threat context,
     hypotheses, leads, TTPs, deep retrohunt summary, execution results) and
     builds a ``full_report`` dict.

  2. LLM executive summary — calls the LLM with the assembled data to produce
     a concise 3-6 sentence executive summary suitable for non-technical
     stakeholders.  Soft-fails if LLM is unavailable.

The completed report is persisted to ``hunt_reports`` via ``db.create_hunt_report``.
The hunt package status is updated to ``completed``.

This node can be called:
  a) Automatically at the end of a successful execution run (triggered by the
     executor after results are collected).
  b) Manually via ``POST /packages/{id}/report`` by the operator at any time
     after the package is approved (even with no execution results).
"""

from __future__ import annotations

import logging
import time
from datetime import datetime, timezone
from typing import Any

from backend.threat_hunting.agents.llm_bridge import build_prompt, call_llm

logger = logging.getLogger(__name__)


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── Deterministic report assembly ─────────────────────────────────────────────


def _evidence_summary(evidence_items: list[dict[str, Any]]) -> dict[str, Any]:
    ioc_total = sum(int(e.get("ioc_count", 0)) for e in evidence_items)
    return {
        "total_items": len(evidence_items),
        "ioc_count": ioc_total,
        "item_types": list({e.get("item_type", "unknown") for e in evidence_items}),
    }


def _retrohunt_summary(deep_retrohunt: dict[str, Any] | None) -> dict[str, Any] | None:
    if not deep_retrohunt:
        return None
    return {
        "total_iocs": deep_retrohunt.get("total_ioc_count", 0),
        "noisy_iocs": deep_retrohunt.get("noisy_ioc_count", 0),
        "high_noise_iocs": deep_retrohunt.get("high_noise_ioc_count", 0),
        "spl_macro_name": deep_retrohunt.get("spl_macro_name", ""),
        "search_hint": deep_retrohunt.get("search_hint", ""),
    }


def _execution_summary(task_results: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        {
            "id": r.get("id", ""),
            "status": r.get("status", ""),
            "earliest": r.get("earliest", ""),
            "latest": r.get("latest", ""),
            "event_count": len(r.get("raw_result") or []),
            "interpreted_findings": r.get("interpreted_findings", ""),
            "completed_at": r.get("completed_at", ""),
        }
        for r in task_results
    ]


def assemble_report(
    hunt_package: dict[str, Any],
    generation_record: dict[str, Any],
    evidence_items: list[dict[str, Any]],
    task_results: list[dict[str, Any]],
    *,
    executive_summary: str = "",
    findings: str = "",
) -> dict[str, Any]:
    """Build the full_report dict from all available data."""
    hypotheses = generation_record.get("hypotheses") or []
    hunting_leads = generation_record.get("hunting_leads") or []
    ttp_analysis = generation_record.get("ttp_analysis")
    deep_retrohunt = generation_record.get("deep_retrohunt")
    query_drafts = generation_record.get("query_drafts") or []
    threat_context = generation_record.get("threat_context")

    # Derive recommendations from hypotheses and execution results
    recommendations: list[str] = []
    for h in hypotheses[:3]:
        title = h.get("title", "")
        if title:
            recommendations.append(f"Investigate: {title}")
    completed_results = [r for r in task_results if r.get("status") == "completed"]
    if completed_results:
        total_events = sum(len(r.get("raw_result") or []) for r in completed_results)
        if total_events > 0:
            recommendations.append(
                f"Review {total_events} SIEM event(s) identified during retrohunt execution."
            )
        else:
            recommendations.append(
                "No SIEM events matched the retrohunt IOCs — consider broadening the time range or reviewing IOC quality."
            )

    return {
        "executive_summary": executive_summary,
        "hunt_name": hunt_package.get("name", ""),
        "hunt_id": hunt_package.get("id", ""),
        "generated_at": _utc_now(),
        "generated_by": None,
        "package_status": hunt_package.get("status", ""),
        "evidence_summary": _evidence_summary(evidence_items),
        "threat_context": threat_context,
        "hypotheses": hypotheses,
        "hunting_leads": hunting_leads,
        "deep_retrohunt_summary": _retrohunt_summary(deep_retrohunt),
        "ttp_analysis": ttp_analysis,
        "query_drafts_count": len(query_drafts),
        "execution_results": _execution_summary(task_results),
        "recommendations": recommendations,
        # issue-008-2C-C: placed last, generated by a separate LLM call
        "findings": findings or None,
    }


# ── LLM executive summary ─────────────────────────────────────────────────────

_EXEC_SUMMARY_FORMAT = (
    "A plain-text executive summary of 3-6 sentences. "
    "No markdown, no bullet points. "
    "Suitable for a non-technical stakeholder."
)


async def _generate_executive_summary(
    full_report: dict[str, Any],
    *,
    provider_name: str | None,
    model_name: str | None,
) -> str:

    threat_ctx = full_report.get("threat_context") or {}
    hypotheses = full_report.get("hypotheses") or []
    exec_results = full_report.get("execution_results") or []
    retro_summary = full_report.get("deep_retrohunt_summary") or {}

    hyp_titles = ", ".join(h.get("title", "") for h in hypotheses[:3] if h.get("title"))
    total_events = sum(r.get("event_count", 0) for r in exec_results)
    findings_texts = [
        r["interpreted_findings"]
        for r in exec_results
        if r.get("interpreted_findings") and "unavailable" not in r.get("interpreted_findings", "")
    ]

    context_sections = [
        ("Hunt Name", full_report.get("hunt_name", "")),
        ("Threat Summary", str(threat_ctx.get("summary", "Not available"))),
        (
            "Top Hypotheses",
            hyp_titles or "None generated",
        ),
        (
            "Retrohunt",
            f"{retro_summary.get('total_iocs', 0)} IOCs searched, "
            f"{total_events} SIEM events matched"
            if retro_summary
            else "No retrohunt performed",
        ),
        (
            "Key Findings",
            "\n".join(findings_texts[:3]) if findings_texts else "No execution findings available",
        ),
    ]

    system, user = build_prompt(
        task_description=(
            "Write a concise executive summary for a completed Threat Hunt. "
            "Explain what was hunted, what was found, and what action is recommended. "
            "Write for a non-technical stakeholder."
        ),
        context_sections=context_sections,
        output_format=_EXEC_SUMMARY_FORMAT,
        additional_instructions=(
            "Do NOT use markdown. Do NOT use bullet points. "
            "3-6 plain sentences only. Be factual — do not invent details."
        ),
    )

    return await call_llm(
        user,
        system=system,
        provider_name=provider_name,
        model=model_name,
        max_tokens=400,
    )


# ── LLM Findings/Conclusion section (issue-008-2C-C) ────────────────────────

_FINDINGS_FORMAT = (
    "A detailed Findings/Conclusion section in plain text. "
    "4-8 paragraphs or 10-20 sentences. "
    "More detailed than the executive summary. "
    "Synthesize the most important facts from the entire hunt: "
    "specific IOCs of interest, confirmed TTPs, hunting-lead outcomes, "
    "SIEM evidence, and a clear conclusion statement. "
    "Suitable for a security analyst. No markdown formatting."
)


async def _generate_findings(
    full_report: dict[str, Any],
    *,
    provider_name: str | None,
    model_name: str | None,
) -> str:
    """Generate a detailed Findings/Conclusion section via LLM.

    Placed at the bottom of the report, after Recommendations.
    More detailed than the executive summary; synthesizes the full hunt outcome.
    Returns a plain-text string; empty string on error (soft-fail).
    """
    threat_ctx = full_report.get("threat_context") or {}
    hypotheses = full_report.get("hypotheses") or []
    exec_results = full_report.get("execution_results") or []
    retro_summary = full_report.get("deep_retrohunt_summary") or {}
    ttp_analysis = full_report.get("ttp_analysis") or {}
    recommendations = full_report.get("recommendations") or []

    hyp_lines = "\n".join(
        f"- [{h.get('id', '')}] {h.get('title', '')} ({h.get('relevance', '')}) — "
        f"{h.get('description', '')[:200]}"
        for h in hypotheses
    )
    total_events = sum(r.get("event_count", 0) for r in exec_results)
    findings_texts = "\n".join(
        r.get("interpreted_findings", "")
        for r in exec_results
        if r.get("interpreted_findings") and "unavailable" not in r.get("interpreted_findings", "")
    )
    techniques = ", ".join(
        f"{t.get('technique_id', '')} {t.get('technique_name', '')}"
        for t in (ttp_analysis.get("techniques") or [])[:6]
    )
    ioc_count = retro_summary.get("total_iocs") or 0
    noisy_iocs = retro_summary.get("noisy_iocs") or 0

    context_sections = [
        ("Hunt Name", full_report.get("hunt_name", "")),
        ("Threat Actor / Campaign", str(threat_ctx.get("summary", "Not available"))[:500]),
        ("Attack Vector", str(threat_ctx.get("attack_vector", "Unknown"))),
        ("Confidence", str(threat_ctx.get("confidence", "Unknown"))),
        (
            "Hypotheses",
            hyp_lines[:1500] if hyp_lines else "None generated",
        ),
        (
            "IOC Retrohunt",
            f"{ioc_count} IOCs searched ({noisy_iocs} noisy/filtered), "
            f"{total_events} SIEM events matched"
            if retro_summary
            else "Not performed",
        ),
        (
            "SIEM Execution Findings",
            findings_texts[:1000] if findings_texts else "No execution run",
        ),
        ("MITRE ATT&CK Techniques", techniques or "Not mapped"),
        ("Recommendations", "; ".join(recommendations[:5]) or "None"),
    ]

    system, user = build_prompt(
        task_description=(
            "Write a comprehensive Findings/Conclusion section for a completed Threat Hunt report. "
            "This section goes at the END of the report, after Recommendations. "
            "It should be more detailed than the executive summary, intended for security analysts. "
            "Cover: key IOCs and their significance, confirmed or suspected adversary behaviours, "
            "what the SIEM evidence did or did not reveal, assessment of each major hypothesis, "
            "and a clear conclusion about whether the threat was detected in the environment."
        ),
        context_sections=context_sections,
        output_format=_FINDINGS_FORMAT,
        additional_instructions=(
            "Write in plain paragraphs (no markdown, no bullets). "
            "Be specific — reference IOCs, technique IDs, and event counts where available. "
            "Conclude with a clear statement of confidence and recommended next steps. "
            "If no SIEM execution was performed, state that clearly and base conclusions "
            "on the available threat intelligence and hypotheses only."
        ),
    )

    try:
        return await call_llm(
            user,
            system=system,
            provider_name=provider_name,
            model=model_name,
            max_tokens=1200,
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("report_writer: findings generation failed: %s", exc)
        return _build_fallback_findings(full_report)


def _build_fallback_findings(full_report: dict[str, Any]) -> str:
    """Build a templated Findings/Conclusion when the LLM is unavailable."""
    hypotheses = full_report.get("hypotheses") or []
    exec_results = full_report.get("execution_results") or []
    total_events = sum(r.get("event_count", 0) for r in exec_results)
    retro = full_report.get("deep_retrohunt_summary") or {}
    hunt_name = full_report.get("hunt_name", "this hunt")

    parts: list[str] = [
        f"FINDINGS AND CONCLUSION — {hunt_name.upper()}",
        "",
        f"This hunt assessed {len(hypotheses)} hypothesis(es) based on the collected threat "
        "intelligence evidence.",
    ]
    if hypotheses:
        parts.append(
            "The following hypotheses were evaluated: "
            + "; ".join(
                f"{h.get('id', '')} {h.get('title', '')} "
                f"(relevance: {h.get('relevance', 'unknown')})"
                for h in hypotheses[:5]
            )
            + "."
        )
    if retro:
        parts.append(
            f"The deep retrohunt searched {retro.get('total_iocs', 0)} IOCs "
            f"({retro.get('noisy_iocs', 0)} flagged as noisy)."
        )
    if total_events > 0:
        parts.append(
            f"SIEM execution identified {total_events} event(s) matching the hunt criteria. "
            "Manual review of these events is recommended to determine whether they represent "
            "genuine threat activity or false positives."
        )
    else:
        parts.append(
            "No SIEM execution events matched the hunt criteria at the time of report generation. "
            "This may indicate the threat has not been active in this environment, "
            "or that the search time range or IOC set requires adjustment."
        )
    parts += [
        "",
        "This report was generated automatically. The findings and recommendations should be "
        "reviewed by a qualified threat analyst before any action is taken.",
    ]
    return "\n".join(parts)


# ── Public entry point ────────────────────────────────────────────────────────


async def write_report(
    hunt_package_id: str,
    *,
    run_id: str | None = None,
    provider_name: str | None = None,
    model_name: str | None = None,
    created_by: str | None = None,
    report_formats: dict[str, bool] | None = None,
) -> dict[str, Any]:
    """Assemble and persist the Hunt Report for a completed/approved package.

    When *run_id* is supplied the report is scoped to that specific run:
    - generation record loaded by run_id
    - task_results filtered to that run_id
    - report stored with run_id

    When *run_id* is None the latest run is used (back-compat).

    Loads all relevant data from the DB, assembles the structured report,
    generates an LLM executive summary (soft-fail), and writes to hunt_reports.

    Returns the persisted report dict.
    """
    start = time.monotonic()
    from backend.threat_hunting import db as th_db

    # Load all source data
    pkg = await th_db.get_hunt_package(hunt_package_id)
    if not pkg:
        raise ValueError(f"Hunt package {hunt_package_id!r} not found")

    generation_record = (
        await th_db.get_generation_record_public(hunt_package_id, run_id=run_id) or {}
    )
    evidence_items = await th_db.list_evidence_items(hunt_package_id)
    # Scope SIEM results to this run if run_id is provided
    if run_id:
        task_results = await th_db.list_task_results_by_run(run_id)
    else:
        task_results = await th_db.list_task_results(hunt_package_id)

    # Stage 1: deterministic assembly (no LLM)
    full_report = assemble_report(
        pkg,
        generation_record,
        evidence_items,
        task_results,
    )

    # Stage 2: LLM executive summary (soft-fail)
    executive_summary = ""
    try:
        from backend.llm.errors import LLMDisabledError

        executive_summary = await _generate_executive_summary(
            full_report, provider_name=provider_name, model_name=model_name
        )
    except Exception as exc:
        from backend.llm.errors import LLMDisabledError

        if isinstance(exc, LLMDisabledError):
            logger.info("report_writer: LLM disabled — skipping executive summary")
        else:
            logger.exception("report_writer: executive summary generation failed: %s", exc)
        executive_summary = _build_fallback_summary(full_report)

    full_report["executive_summary"] = executive_summary

    # Stage 2b: LLM Findings/Conclusion section (issue-008-2C-C, soft-fail)
    findings = ""
    try:
        from backend.llm.errors import LLMDisabledError

        findings = await _generate_findings(
            full_report, provider_name=provider_name, model_name=model_name
        )
    except Exception as exc:
        from backend.llm.errors import LLMDisabledError

        if isinstance(exc, LLMDisabledError):
            logger.info("report_writer: LLM disabled — using templated findings")
        else:
            logger.warning("report_writer: findings generation failed: %s", exc)
        findings = _build_fallback_findings(full_report)
    full_report["findings"] = findings or None

    # Stage 3: resolve which formats to generate (default from loader if not provided)
    if report_formats is None:
        try:
            from backend.config.loader import load_th_report_formats

            report_formats = load_th_report_formats()
        except Exception:
            report_formats = {"pdf": True, "markdown": True}

    # Render ancillary formats — stored as metadata fields for download endpoints
    markdown_content: str | None = None
    if report_formats.get("markdown", True):
        try:
            markdown_content = render_report_markdown(full_report)
        except Exception as exc:
            logger.warning("report_writer: markdown render failed: %s", exc)

    # PDF is generated on-demand at the download endpoint (not stored as a blob)
    # to keep DB lean. We still note whether it was requested.
    full_report["_report_formats"] = report_formats
    if markdown_content:
        full_report["_markdown"] = markdown_content

    # Stage 4: persist (with run_id linkage for independent re-run reports)
    report = await th_db.create_hunt_report(
        hunt_package_id,
        executive_summary=executive_summary,
        full_report=full_report,
        created_by=created_by,
        run_id=run_id,
    )

    # Update package to completed if it was approved
    if pkg.get("status") == "approved":
        await th_db.update_hunt_package(hunt_package_id, status="completed")

    elapsed = time.monotonic() - start
    logger.info("report_writer: report generated for %s in %.2fs", hunt_package_id[:8], elapsed)
    return report


# ── Markdown renderer ─────────────────────────────────────────────────────────


def render_report_markdown(full_report: dict[str, Any]) -> str:
    """Render the full_report dict as a Markdown document string."""
    lines: list[str] = []

    def _h(level: int, text: str) -> None:
        lines.append(f"{'#' * level} {text}\n")

    def _p(text: str) -> None:
        if text:
            lines.append(f"{text}\n")

    def _li(text: str) -> None:
        lines.append(f"- {text}")

    def _code(text: str, lang: str = "") -> None:
        lines.append(f"```{lang}")
        lines.append(text)
        lines.append("```\n")

    _h(1, f"Threat Hunt Report: {full_report.get('hunt_name', 'Unnamed Hunt')}")
    lines.append(f"**Hunt ID:** {full_report.get('hunt_id', '')}")
    lines.append(f"**Generated At:** {full_report.get('generated_at', '')}")
    lines.append(f"**Status:** {full_report.get('package_status', '')}\n")

    exec_summary = full_report.get("executive_summary", "")
    if exec_summary:
        _h(2, "Executive Summary")
        _p(exec_summary)

    ev = full_report.get("evidence_summary") or {}
    _h(2, "Evidence Summary")
    lines.append(f"- Evidence items: {ev.get('total_items', 0)}")
    lines.append(f"- IOCs extracted: {ev.get('ioc_count', 0)}")
    lines.append(f"- Item types: {', '.join(ev.get('item_types', []) or [])}\n")

    tc = full_report.get("threat_context") or {}
    if tc and not tc.get("parse_error"):
        _h(2, "Threat Context")
        if tc.get("summary"):
            _p(tc["summary"])
        for k, label in [
            ("threat_actor", "Threat Actor"),
            ("campaign_name", "Campaign"),
            ("attack_vector", "Attack Vector"),
            ("confidence", "Confidence"),
        ]:
            if tc.get(k):
                lines.append(f"- **{label}:** {tc[k]}")
        for family in tc.get("malware_families") or []:
            lines.append(f"- **Malware Family:** {family}")
        lines.append("")

    hypotheses = full_report.get("hypotheses") or []
    if hypotheses:
        _h(2, f"Hypotheses ({len(hypotheses)})")
        for h in hypotheses:
            _h(3, f"[{h.get('id', '')}] {h.get('title', '')}")
            lines.append(f"**Relevance:** {h.get('relevance', '')}")
            _p(h.get("description", ""))
            if h.get("justification"):
                _p(f"*Justification: {h['justification']}*")
            if h.get("ioc_basis"):
                _p(f"*IOC Basis: {', '.join(str(i) for i in h['ioc_basis'][:5])}*")
            # issue-006-E: suggested_actions
            if h.get("suggested_actions"):
                lines.append("**Suggested Actions:**")
                for action in h["suggested_actions"]:
                    lines.append(f"  - `{action}`")
                lines.append("")

    hunting_leads = full_report.get("hunting_leads") or []
    if hunting_leads:
        _h(2, f"Hunting Leads ({len(hunting_leads)})")
        for lead in hunting_leads:
            _h(3, f"[{lead.get('id', '')}] {lead.get('title', '')}")
            lines.append(
                f"**Priority:** {lead.get('priority', '')}  **Hypothesis:** {lead.get('hypothesis_id', '')}"
            )
            _p(lead.get("description", ""))
            for task in lead.get("tasks") or []:
                lines.append(
                    f"  - **{task.get('id', '')} {task.get('title', '')}** — {task.get('description', '')}"
                )
            lines.append("")

    retro = full_report.get("deep_retrohunt_summary") or {}
    if retro:
        _h(2, "Deep Retrohunt Summary")
        lines.append(
            f"- IOCs: {retro.get('total_iocs', 0)} total, {retro.get('noisy_iocs', 0)} noisy, {retro.get('high_noise_iocs', 0)} high-noise"
        )
        if retro.get("spl_macro_name"):
            lines.append(f"- SPL Macro: `{retro['spl_macro_name']}`")
        if retro.get("search_hint"):
            lines.append(f"- Search hint: {retro['search_hint']}")
        lines.append("")

    ttp = full_report.get("ttp_analysis") or {}
    if ttp and not ttp.get("parse_error"):
        _h(2, "TTP Analysis")
        if ttp.get("summary"):
            _p(ttp["summary"])
        for t in ttp.get("techniques") or []:
            lines.append(
                f"- **{t.get('technique_id', '')} {t.get('technique_name', '')}** ({t.get('tactic', '')}): {t.get('description', '')}"
            )
        for opp in ttp.get("detection_opportunities") or []:
            lines.append(f"  - Detection: {opp}")
        lines.append("")

    exec_results = full_report.get("execution_results") or []
    if exec_results:
        _h(2, f"Execution Results ({len(exec_results)} run(s))")
        for r in exec_results:
            lines.append(
                f"- **{r.get('id', '')}** status={r.get('status', '')} events={r.get('event_count', 0)}"
            )
            if r.get("interpreted_findings"):
                _p(f"  *{r['interpreted_findings']}*")
        lines.append("")

    recs = full_report.get("recommendations") or []
    if recs:
        _h(2, "Recommendations")
        for rec in recs:
            _li(rec)
        lines.append("")

    # issue-008-2C-C: Findings/Conclusion — placed LAST
    findings = full_report.get("findings")
    if findings:
        _h(2, "Findings and Conclusion")
        _p(findings)
        lines.append("")

    return "\n".join(lines)


# ── PDF renderer ──────────────────────────────────────────────────────────────


def render_report_pdf(full_report: dict[str, Any]) -> bytes:
    """Render the full_report dict as a PDF byte string using reportlab.

    issue-006-F additions:
    - Cover header block with colored rule and metadata row
    - Page numbers via onFirstPage/onLaterPages callbacks (bottom-center)
    - Tables for Evidence Summary, TTP Techniques, and Execution Results
    - Relevance/priority cells use color (red=high, amber=medium, gray=low)
    - Colored dark-blue rule above each H2 section header
    """
    from io import BytesIO

    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        HRFlowable,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    PAGE_W, PAGE_H = A4
    LEFT_MARGIN = 2 * cm
    RIGHT_MARGIN = 2 * cm
    TOP_MARGIN = 2.5 * cm
    BOT_MARGIN = 2 * cm

    buf = BytesIO()

    # ── Page callbacks for page numbers ──────────────────────────────────────
    def _add_page_number(canvas, doc):  # type: ignore[no-untyped-def]
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#6b7280"))
        page_num = canvas.getPageNumber()
        canvas.drawCentredString(PAGE_W / 2.0, BOT_MARGIN * 0.5, f"Page {page_num}")
        canvas.restoreState()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=RIGHT_MARGIN,
        leftMargin=LEFT_MARGIN,
        topMargin=TOP_MARGIN,
        bottomMargin=BOT_MARGIN,
    )
    styles = getSampleStyleSheet()
    h1_style = ParagraphStyle(
        "CoverH1",
        parent=styles["Heading1"],
        fontSize=18,
        spaceAfter=4,
        textColor=colors.HexColor("#e5e7eb"),
    )
    h2_style = ParagraphStyle(
        "SectionH2",
        parent=styles["Heading2"],
        fontSize=13,
        spaceAfter=4,
        textColor=colors.HexColor("#d1d5db"),
        spaceBefore=8,
    )
    h3_style = styles["Heading3"]
    body_style = styles["BodyText"]
    meta_style = ParagraphStyle(
        "Meta",
        parent=body_style,
        fontSize=9,
        textColor=colors.HexColor("#9ca3af"),
    )
    code_style = ParagraphStyle(
        "Code",
        parent=body_style,
        fontName="Courier",
        fontSize=8,
        leftIndent=12,
        spaceAfter=4,
    )

    # Color constants for tables/priority cells
    _COL_HEADER_BG = colors.HexColor("#1e3a5f")
    _COL_HEADER_FG = colors.HexColor("#bfdbfe")
    _COL_ROW_ALT = colors.HexColor("#111827")
    _COL_ROW_NORM = colors.HexColor("#1f2937")
    _COL_HIGH = colors.HexColor("#7f1d1d")
    _COL_MED = colors.HexColor("#78350f")
    _COL_LOW = colors.HexColor("#374151")
    _COL_BORDER = colors.HexColor("#374151")
    _COL_DARK_RULE = colors.HexColor("#1e3a5f")

    story: list = []

    def _esc(text: str) -> str:
        """Escape XML chars for reportlab Paragraph."""
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    def _h1(text: str) -> None:
        story.append(Paragraph(_esc(text), h1_style))

    def _h2(text: str) -> None:
        story.append(Spacer(1, 6))
        story.append(HRFlowable(width="100%", thickness=2, color=_COL_DARK_RULE))
        story.append(Paragraph(_esc(text), h2_style))

    def _h3(text: str) -> None:
        story.append(Paragraph(_esc(text), h3_style))

    def _p(text: str, style: ParagraphStyle | None = None) -> None:
        if text:
            story.append(Paragraph(_esc(text), style or body_style))

    def _p_raw(html: str, style: ParagraphStyle | None = None) -> None:
        """Emit a paragraph with pre-escaped HTML tags (bold/italic allowed)."""
        if html:
            story.append(Paragraph(html, style or body_style))

    def _sp(h: int = 4) -> None:
        story.append(Spacer(1, h))

    # ── Cover header ─────────────────────────────────────────────────────────
    hunt_name = full_report.get("hunt_name", "Unnamed Hunt")
    _h1(f"Threat Hunt Report: {hunt_name}")
    story.append(HRFlowable(width="100%", thickness=3, color=_COL_DARK_RULE))
    _sp(6)

    meta_parts = []
    if full_report.get("hunt_id"):
        meta_parts.append(f"Hunt ID: {full_report['hunt_id']}")
    if full_report.get("generated_at"):
        meta_parts.append(f"Generated: {full_report['generated_at']}")
    if full_report.get("package_status"):
        meta_parts.append(f"Status: {full_report['package_status']}")
    if full_report.get("generated_by"):
        meta_parts.append(f"By: {full_report['generated_by']}")
    if meta_parts:
        story.append(Paragraph("  |  ".join(_esc(m) for m in meta_parts), meta_style))
    _sp(8)

    exec_summary = full_report.get("executive_summary", "")
    if exec_summary:
        _h2("Executive Summary")
        _p(exec_summary)

    # ── Evidence Summary — Table ──────────────────────────────────────────────
    ev = full_report.get("evidence_summary") or {}
    _h2("Evidence Summary")
    try:
        ev_rows = [
            ["Metric", "Value"],
            ["Evidence Items", str(ev.get("total_items", 0))],
            ["IOCs Extracted", str(ev.get("ioc_count", 0))],
            ["Evidence Types", ", ".join(ev.get("item_types", []) or [])],
        ]
        ev_table = Table(ev_rows, colWidths=[5 * cm, None])
        ev_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), _COL_HEADER_BG),
                    ("TEXTCOLOR", (0, 0), (-1, 0), _COL_HEADER_FG),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_COL_ROW_NORM, _COL_ROW_ALT]),
                    ("GRID", (0, 0), (-1, -1), 0.5, _COL_BORDER),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ]
            )
        )
        story.append(ev_table)
    except Exception:  # noqa: BLE001
        _p(f"Items: {ev.get('total_items', 0)}  |  IOCs: {ev.get('ioc_count', 0)}")

    # ── Threat Context ────────────────────────────────────────────────────────
    tc = full_report.get("threat_context") or {}
    if tc and not tc.get("parse_error"):
        _h2("Threat Context")
        if tc.get("summary"):
            _p(tc["summary"])
        for k, label in [
            ("threat_actor", "Threat Actor"),
            ("campaign_name", "Campaign"),
            ("attack_vector", "Attack Vector"),
            ("confidence", "Confidence"),
        ]:
            if tc.get(k):
                _p_raw(f"<b>{label}:</b> {_esc(str(tc[k]))}")
        for f in tc.get("malware_families") or []:
            _p_raw(f"<b>Malware Family:</b> {_esc(str(f))}")

    # ── Hypotheses ────────────────────────────────────────────────────────────
    hypotheses = full_report.get("hypotheses") or []
    if hypotheses:
        _h2(f"Hypotheses ({len(hypotheses)})")
        for h in hypotheses:
            relevance = h.get("relevance", "")
            _h3(f"[{h.get('id', '')}] {h.get('title', '')}")
            _p_raw(f"<b>Relevance:</b> {_esc(relevance)}")
            _p(h.get("description", ""))
            if h.get("justification"):
                _p_raw(f"<i>{_esc(h['justification'])}</i>")
            if h.get("ioc_basis"):
                _p_raw(f"<i>IOC Basis: {_esc(', '.join(str(i) for i in h['ioc_basis'][:5]))}</i>")
            if h.get("suggested_actions"):
                _p_raw("<b>Suggested Actions:</b>")
                for action in h["suggested_actions"]:
                    _p_raw(f"• {_esc(str(action))}")
            _sp()

    # ── Hunting Leads ─────────────────────────────────────────────────────────
    hunting_leads = full_report.get("hunting_leads") or []
    if hunting_leads:
        _h2(f"Hunting Leads ({len(hunting_leads)})")
        for lead in hunting_leads:
            _h3(f"[{lead.get('id', '')}] {lead.get('title', '')}")
            _p_raw(
                f"<b>Priority:</b> {_esc(lead.get('priority', ''))}  "
                f"<b>Hypothesis:</b> {_esc(lead.get('hypothesis_id', ''))}"
            )
            _p(lead.get("description", ""))
            for task in lead.get("tasks") or []:
                _p_raw(
                    f"• <b>{_esc(task.get('id', ''))} {_esc(task.get('title', ''))}</b> "
                    f"— {_esc(task.get('description', ''))}"
                )
            _sp()

    # ── Deep Retrohunt Summary ────────────────────────────────────────────────
    retro = full_report.get("deep_retrohunt_summary") or {}
    if retro:
        _h2("Deep Retrohunt Summary")
        _p_raw(
            f"IOCs: {retro.get('total_iocs', 0)} total, "
            f"{retro.get('noisy_iocs', 0)} noisy, "
            f"{retro.get('high_noise_iocs', 0)} high-noise"
        )
        if retro.get("spl_macro_name"):
            story.append(Paragraph(_esc(str(retro["spl_macro_name"])), code_style))
        if retro.get("search_hint"):
            _p(str(retro["search_hint"]))

    # ── TTP Analysis — Table ──────────────────────────────────────────────────
    ttp = full_report.get("ttp_analysis") or {}
    if ttp and not ttp.get("parse_error"):
        _h2("TTP Analysis")
        if ttp.get("summary"):
            _p(ttp["summary"])
        techniques = ttp.get("techniques") or []
        if techniques:
            try:
                ttp_rows = [["ID", "Name", "Tactic", "Detection"]]
                for t in techniques:
                    ttp_rows.append(
                        [
                            t.get("technique_id", ""),
                            t.get("technique_name", ""),
                            t.get("tactic", ""),
                            t.get("description", "")[:80],
                        ]
                    )
                ttp_table = Table(ttp_rows, colWidths=[2.2 * cm, 4 * cm, 3 * cm, None])
                ttp_style = TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), _COL_HEADER_BG),
                        ("TEXTCOLOR", (0, 0), (-1, 0), _COL_HEADER_FG),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 8),
                        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_COL_ROW_NORM, _COL_ROW_ALT]),
                        ("GRID", (0, 0), (-1, -1), 0.5, _COL_BORDER),
                        ("LEFTPADDING", (0, 0), (-1, -1), 5),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                        ("TOPPADDING", (0, 0), (-1, -1), 3),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("WORDWRAP", (3, 1), (3, -1), "CJK"),
                    ]
                )
                ttp_table.setStyle(ttp_style)
                story.append(ttp_table)
            except Exception:  # noqa: BLE001
                for t in techniques:
                    _p_raw(
                        f"• <b>{_esc(t.get('technique_id', ''))} "
                        f"{_esc(t.get('technique_name', ''))}</b> "
                        f"({_esc(t.get('tactic', ''))}): "
                        f"{_esc(t.get('description', ''))}"
                    )
        for opp in ttp.get("detection_opportunities") or []:
            _p_raw(f"  Detection: {_esc(str(opp))}")

    # ── Execution Results — Table ─────────────────────────────────────────────
    exec_results = full_report.get("execution_results") or []
    if exec_results:
        _h2(f"Execution Results ({len(exec_results)} run(s))")
        try:
            er_rows = [["Run ID", "Status", "Events", "Findings"]]
            for r in exec_results:
                status = r.get("status", "")
                er_rows.append(
                    [
                        str(r.get("id", ""))[:12],
                        status,
                        str(r.get("event_count", 0)),
                        (r.get("interpreted_findings") or "")[:80],
                    ]
                )
            er_table = Table(er_rows, colWidths=[3 * cm, 2.5 * cm, 2 * cm, None])
            er_style = TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), _COL_HEADER_BG),
                    ("TEXTCOLOR", (0, 0), (-1, 0), _COL_HEADER_FG),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_COL_ROW_NORM, _COL_ROW_ALT]),
                    ("GRID", (0, 0), (-1, -1), 0.5, _COL_BORDER),
                    ("LEFTPADDING", (0, 0), (-1, -1), 5),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
            er_table.setStyle(er_style)
            story.append(er_table)
        except Exception:  # noqa: BLE001
            for r in exec_results:
                _p_raw(
                    f"• <b>{_esc(str(r.get('id', '')))}</b> status={_esc(r.get('status', ''))} "
                    f"events={r.get('event_count', 0)}"
                )
                if r.get("interpreted_findings"):
                    _p_raw(f"  <i>{_esc(str(r['interpreted_findings']))}</i>")

    # ── Recommendations ───────────────────────────────────────────────────────
    recs = full_report.get("recommendations") or []
    if recs:
        _h2("Recommendations")
        for rec in recs:
            _p_raw(f"• {_esc(str(rec))}")

    # ── Findings and Conclusion (issue-008-2C-C) — placed LAST ────────────────
    findings = full_report.get("findings")
    if findings:
        _h2("Findings and Conclusion")
        # Split into paragraphs (double newline) for readable PDF rendering
        for para in str(findings).split("\n\n"):
            para = para.strip()
            if para:
                _p(_esc(para))
        _sp(8)

    doc.build(story, onFirstPage=_add_page_number, onLaterPages=_add_page_number)
    return buf.getvalue()


def _build_fallback_summary(full_report: dict[str, Any]) -> str:
    """Build a deterministic plain-text executive summary without the LLM."""
    hunt_name = full_report.get("hunt_name", "this hunt")
    hypotheses = full_report.get("hypotheses") or []
    retro = full_report.get("deep_retrohunt_summary") or {}
    exec_results = full_report.get("execution_results") or []
    total_events = sum(r.get("event_count", 0) for r in exec_results)
    ioc_count = retro.get("total_iocs", 0)
    threat_ctx = full_report.get("threat_context") or {}
    threat_summary = str(threat_ctx.get("summary", "")).strip()

    parts: list[str] = []
    parts.append(
        f"Threat hunt '{hunt_name}' has been completed with "
        f"{len(hypotheses)} hypothesis(es) generated."
    )
    if threat_summary:
        parts.append(threat_summary)
    if ioc_count:
        parts.append(
            f"The deep retrohunt searched {ioc_count} IOC(s) against the SIEM, "
            f"returning {total_events} event(s)."
        )
    elif exec_results:
        parts.append(f"Execution produced {total_events} SIEM event(s).")
    parts.append("Review the full report for detailed findings and recommendations.")
    return " ".join(parts)
